project:
  type: website

website:
  title: "y"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: news.qmd
        text: news

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



